CREATE TABLE usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL,
  email VARCHAR(100) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  data_nascimento DATE,
  cep VARCHAR(20),
  endereco VARCHAR(150),
  numero VARCHAR(20),
  complemento VARCHAR(50),
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE bairros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(100) NOT NULL
);
INSERT INTO bairros (nome) VALUES
('14 de Novembro'),
('Alto Alegre'),
('Alto da Glória'),
('Bairro Universitário'),
('Bela Vista'),
('Brazmadeira'),
('Brasmadeira'),
('Brasília'),
('Cajati'),
('Cancelli'),
('Cascavel Velho'),
('Centro'),
('Claudemir'),
('Coqueiral'),
('Country'),
('Cristo Rei'),
('Fag'),
('Floresta'),
('Guarujá'),
('Interlagos'),
('Jardim Alvorada'),
('Jardim América'),
('Jardim Canadá'),
('Jardim Colônia'),
('Jardim Cristal'),
('Jardim Esmeralda'),
('Jardim Europa'),
('Jardim Itália'),
('Jardim Melissa'),
('Jardim Nova Itália'),
('Jardim Palmeiras'),
('Jardim Presidente'),
('Jardim Riviera'),
('Jardim Santa Cruz'),
('Jardim São Paulo'),
('Morumbi'),
('Neva'),
('Parque São Paulo'),
('Periolo'),
('Pioneiros Catarinenses'),
('Portal da Luz'),
('Recanto Tropical'),
('Região do Lago'),
('Santa Cruz'),
('Santa Felicidade'),
('Santos Dumont'),
('São Cristóvão'),
('São Salvador'),
('Tarumã'),
('Universitário'),
('Vila A'),
('Vila B'),
('Vila C'),
('Vila D'),
('Vila Tolentino'),
('West Side');

CREATE TABLE doacoes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome_material VARCHAR(100) NOT NULL,
  quantidade INT NOT NULL,
  tipo_material ENUM('metal','papel','plastico','vidro','outros') NOT NULL,
  bairro_id INT NOT NULL,
  dias_semana VARCHAR(100),
  horarios VARCHAR(100),
  descricao TEXT,
  imagem VARCHAR(255),
  usuario_id INT,
  criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (bairro_id) REFERENCES bairros(id)
);
CREATE TABLE solicitacoes_coleta (
  id INT AUTO_INCREMENT PRIMARY KEY,
  doacao_id INT NOT NULL,
  solicitante_id INT NOT NULL,
  doador_id INT NOT NULL,
  status ENUM('pendente', 'confirmada', 'recusada') DEFAULT 'pendente',
  criada_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

  FOREIGN KEY (doacao_id) REFERENCES doacoes(id),
  FOREIGN KEY (solicitante_id) REFERENCES usuarios(id),
  FOREIGN KEY (doador_id) REFERENCES usuarios(id)
);
